### ISSUE TITLE
Quarkus auto reload doesn't work ./mvnw compile quarkus:dev

### ISSUE THREAD

**Issue by carldea** [hpehl/quarkus-grpc-quickstart#1]
Not sure how to run the client in dev mode whenever I change html, or java code it should be able to reload app. Possible make it optional for protoc of services and objects, being that it's much slower.

$ mvn compile quarkus:dev
13:44:33,579 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.ExceptionInInitializerError
... other stuff
Caused by: java.lang.ClassNotFoundException: io.grpc.examples.routeguide.RouteGuideGrpc$RouteGuideBlockingStub

**Comment by hpehl** [comment]
Closing, since this extension is no longer supported. See README.md
